[package]
org = "ballerinax"
name = "health.fhir.lkcore010.medicationadministration"
version = "1.0.0"
distribution = "2201.8.1"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "MedicationAdministration", "r4", "health.fhir.r4.lkcore010"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.templates"
template = true
